AWSTemplateFormatVersion: 2010-09-09
Description: This is the root template that references all other nested templates


Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cf-vpc.yaml
      TimeoutInMinutes: '10'

#  Beanstalk:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: ./cf-beanstalk.yaml
#      TimeoutInMinutes: '10'

#  ECS:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: ./cf-ecs.yaml
#      TimeoutInMinutes: '10'

Outputs:
  StackRef:
    Value: !Ref VPC
  VPCId:
    Value: !Sub ${VPC.Outputs.VpcId}
  PublicSubnetId:
    Value: !Sub ${VPC.Outputs.PublicSubnetId}

  PrivateSubnetId:
    Value: !Sub ${VPC.Outputs.PrivateSubnetId}

  PrivateSecurityGroup:
    Value: !Sub ${VPC.Outputs.PrivateSecurityGroup}

  PublicSecurityGroup:
    Value: !Sub ${VPC.Outputs.PublicSecurityGroup}


#  S3Bucket:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#s      TemplateURL: https://github.com/dskarbrevik/cloud-excellence-group-project/tree/main/cf-bucket.yaml
