AWSTemplateFormatVersion: 2010-09-09
Description: This is the root template that references all other nested templates

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://us-east-2.console.aws.amazon.com/s3/buckets/codepipeline-us-east-2-394975732130/Test2/cf-templates/cf-vpc.yaml
      TimeoutInMinutes: '10'
Outputs:
  StackRef:
    Value: !Ref VPC
  OutputFromNestedStack:
    Value: !GetAtt VPC.Outputs.S3BucketURL

#  S3Bucket:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#s      TemplateURL: https://github.com/dskarbrevik/cloud-excellence-group-project/tree/main/cf-bucket.yaml
