AWSTemplateFormatVersion: 2010-09-09
Description: This is the root template that references all other nested templates
Outputs:
  PrivateSecurityGroup:
    Value:
      Fn::Sub: ${VPC.Outputs.PrivateSecurityGroup}
  PrivateSubnetId:
    Value:
      Fn::Sub: ${VPC.Outputs.PrivateSubnetId}
  PublicSecurityGroup:
    Value:
      Fn::Sub: ${VPC.Outputs.PublicSecurityGroup}
  PublicSubnetId:
    Value:
      Fn::Sub: ${VPC.Outputs.PublicSubnetId}
  StackRef:
    Value:
      Ref: VPC
  VPCId:
    Value:
      Fn::Sub: ${VPC.Outputs.VpcId}
Resources:
  ECS:
    Properties:
      Parameters:
        AZs:
          Fn::GetAtt:
          - VPC
          - Outputs.PrivateAZs
        SubnetId:
          Fn::GetAtt:
          - VPC
          - Outputs.PrivateSubnetId
        VpcId:
          Fn::GetAtt:
          - VPC
          - Outputs.VpcId
      TemplateURL: https://s3.amazonaws.com/team1-cicd-pipeline-staging/d3e0d243136c688e1d85c6a65d92efd0.template
      TimeoutInMinutes: '10'
    Type: AWS::CloudFormation::Stack
  PublicBastionHost:
    Properties:
      Parameters:
        AZs:
          Fn::GetAtt:
          - VPC
          - Outputs.PrivateAZs
        SubnetId:
          Fn::GetAtt:
          - VPC
          - Outputs.PublicSubnetId
        VpcId:
          Fn::GetAtt:
          - VPC
          - Outputs.VpcId
      TemplateURL: https://s3.amazonaws.com/team1-cicd-pipeline-staging/8d4a1f7cfa2a534e0e3516aca17a7ecf.template
      TimeoutInMinutes: '10'
    Type: AWS::CloudFormation::Stack
  VPC:
    Properties:
      TemplateURL: https://s3.amazonaws.com/team1-cicd-pipeline-staging/7d70958d81c9eeba3765c8cfe429cb77.template
      TimeoutInMinutes: '10'
    Type: AWS::CloudFormation::Stack
